//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barang()
        {
            this.pembelian_item = new HashSet<PembelianItem>();
        }
    
        public System.Guid id { get; set; }
        public string nama_barang { get; set; }
        public Nullable<System.Guid> id_kategori { get; set; }
        public string satuan { get; set; }
        public Nullable<System.DateTime> tanggalinput { get; set; }
        public string subsi { get; set; }
    
        public virtual Kategori kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PembelianItem> pembelian_item { get; set; }
    }
}
