//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int itemid { get; set; }
        public System.Guid adminuserid { get; set; }
        public string itemname { get; set; }
        public int stock { get; set; }
        public string pcsname { get; set; }
        public int price { get; set; }
        public Nullable<int> categoryid { get; set; }
    
        public virtual User User { get; set; }
        public virtual Category Category { get; set; }
    }
}
