//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MerapiGolfLogistikEntities : DbContext
    {
        public MerapiGolfLogistikEntities()
            : base("name=MerapiGolfLogistikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktiva> mg_aktiva { get; set; }
        public virtual DbSet<Barang> mg_barang { get; set; }
        public virtual DbSet<Kategori> mg_kategori { get; set; }
        public virtual DbSet<Pembelian> mg_pembelian { get; set; }
        public virtual DbSet<PembelianItem> mg_pembelian_item { get; set; }
        public virtual DbSet<Pengambilan> mg_pengambilan { get; set; }
        public virtual DbSet<PengambilanItem> mg_pengambilan_item { get; set; }
        public virtual DbSet<Pengembalian> mg_pengembalian { get; set; }
        public virtual DbSet<Supplier> mg_supplier { get; set; }
        public virtual DbSet<User> mg_user { get; set; }
        public virtual DbSet<NotaPembelian> mg_nota_pembelian { get; set; }
        public virtual DbSet<NotaPengambilan> mg_nota_pengambilan { get; set; }
        public virtual DbSet<StokBarang> mg_stok_barang { get; set; }
        public virtual DbSet<StokBarangTotal> mg_stok_barang_total { get; set; }
        public virtual DbSet<TotalPembelian> mg_total_pembelian { get; set; }
        public virtual DbSet<PengambilanPerBarang> mg_pengambilan_per_barang { get; set; }
        public virtual DbSet<PengembalianPerBarang> mg_pengembalian_per_barang { get; set; }
        public virtual DbSet<TotalPengembalian> mg_total_pengembalian { get; set; }
        public virtual DbSet<PengembalianItem> mg_pengembalian_item { get; set; }
        public virtual DbSet<NotaPengembalian> mg_nota_pengembalian { get; set; }
        public virtual DbSet<TotalPengambilan> mg_total_pengambilan { get; set; }
        public virtual DbSet<mg_laporan_gudang> mg_laporan_gudang { get; set; }
    
        [DbFunction("MerapiGolfLogistikEntities", "LaporanGudangFilter")]
        public virtual IQueryable<LaporanGudangFilter_Result> LaporanGudangFilter(Nullable<System.DateTime> tanggalmulai, Nullable<System.DateTime> tanggalselesai)
        {
            var tanggalmulaiParameter = tanggalmulai.HasValue ?
                new ObjectParameter("tanggalmulai", tanggalmulai) :
                new ObjectParameter("tanggalmulai", typeof(System.DateTime));
    
            var tanggalselesaiParameter = tanggalselesai.HasValue ?
                new ObjectParameter("tanggalselesai", tanggalselesai) :
                new ObjectParameter("tanggalselesai", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LaporanGudangFilter_Result>("[MerapiGolfLogistikEntities].[LaporanGudangFilter](@tanggalmulai, @tanggalselesai)", tanggalmulaiParameter, tanggalselesaiParameter);
        }
    }
}
