//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MerapiGolfLogistikEntities : DbContext
    {
        public MerapiGolfLogistikEntities()
            : base("name=MerapiGolfLogistikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktiva> Aktiva { get; set; }
        public virtual DbSet<Barang> Barang { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Pembelian> Pembelian { get; set; }
        public virtual DbSet<PembelianItem> PembelianItem { get; set; }
        public virtual DbSet<Pengambilan> Pengambilan { get; set; }
        public virtual DbSet<PengambilanItem> PengambilanItem { get; set; }
        public virtual DbSet<Pengembalian> Pengembalian { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<NotaPembelian> NotaPembelian { get; set; }
        public virtual DbSet<NotaPengambilan> NotaPengambilan { get; set; }
        public virtual DbSet<StokBarang> StokBarang { get; set; }
        public virtual DbSet<StokBarangTotal> StokBarangTotal { get; set; }
        public virtual DbSet<TotalPembelian> TotalPembelian { get; set; }
    }
}
