//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MerapiGolfLogistikEntities : DbContext
    {
        public MerapiGolfLogistikEntities()
            : base("name=MerapiGolfLogistikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktiva> mg_aktiva { get; set; }
        public virtual DbSet<Barang> mg_barang { get; set; }
        public virtual DbSet<Kategori> mg_kategori { get; set; }
        public virtual DbSet<Pembelian> mg_pembelian { get; set; }
        public virtual DbSet<PembelianItem> mg_pembelian_item { get; set; }
        public virtual DbSet<Pengambilan> mg_pengambilan { get; set; }
        public virtual DbSet<PengambilanItem> mg_pengambilan_item { get; set; }
        public virtual DbSet<Pengembalian> mg_pengembalian { get; set; }
        public virtual DbSet<Supplier> mg_supplier { get; set; }
        public virtual DbSet<User> mg_user { get; set; }
        public virtual DbSet<NotaPembelian> mg_nota_pembelian { get; set; }
        public virtual DbSet<NotaPengambilan> mg_nota_pengambilan { get; set; }
        public virtual DbSet<StokBarang> mg_stok_barang { get; set; }
        public virtual DbSet<StokBarangTotal> mg_stok_barang_total { get; set; }
        public virtual DbSet<TotalPembelian> mg_total_pembelian { get; set; }
    }
}
