//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaPembelian
    {
        public string nama_karyawan { get; set; }
        public string nama_supplier { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<double> total { get; set; }
        public string keterangan { get; set; }
        public string no_nota { get; set; }
    }
}
