//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Collections.Generic;
    
    public partial class PengambilanItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PengambilanItem()
        {
            this.pengembalian = new HashSet<Pengembalian>();
        }
    
        public System.Guid id { get; set; }
        public string no_nota { get; set; }
        public Nullable<System.Guid> id_pembelian_barang { get; set; }
        public Nullable<double> banyak_barang { get; set; }
        public Nullable<System.Guid> id_aktiva { get; set; }
    
        public virtual Aktiva aktiva { get; set; }
        public virtual PembelianItem pembelian_item { get; set; }
        public virtual Pengambilan pengambilan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pengembalian> pengembalian { get; set; }
    }
}
