//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokBarang
    {
        public System.Guid id_barang { get; set; }
        public string nama_barang { get; set; }
        public string no_nota { get; set; }
        public Nullable<System.DateTime> tanggal_masuk { get; set; }
        public Nullable<double> harga_satuan { get; set; }
        public Nullable<double> stok { get; set; }
        public Nullable<System.Guid> id { get; set; }
    }
}
