//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerapiGolfLogistik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalPembelian
    {
        public System.Guid id { get; set; }
        public string no_nota { get; set; }
        public string nama_barang { get; set; }
        public string nama_kategori { get; set; }
        public Nullable<int> banyak_barang { get; set; }
        public Nullable<int> harga_satuan { get; set; }
        public Nullable<int> total_harga { get; set; }
        public string satuan { get; set; }
    }
}
